apiVersion: "v1"
kind: Pod
metadata:
  name: pv-extract
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: pv-extract-pod
      image: registry.redhat.io/ubi9/ubi
      command: ["sleep", "3000"]
      volumeMounts:
      - mountPath: "/ocp4-stig"
        name: ocp4-stig-vol
      - mountPath: "/ocp4-stig-node-worker"
        name: ocp4-stig-node-worker-vol
      - mountPath: "/ocp4-stig-node-master"
        name: ocp4-stig-node-master-vol
      - mountPath: "/rhcos4-stig-worker"
        name: rhcos4-stig-worker-vol
      - mountPath: "/rhcos4-stig-master"
        name: rhcos4-stig-master-vol
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ALL]
  volumes:
    - name: ocp4-stig-vol
      persistentVolumeClaim:
        claimName: ocp4-stig
    - name: ocp4-stig-node-worker-vol
      persistentVolumeClaim:
        claimName: ocp4-stig-node-worker
    - name: ocp4-stig-node-master-vol
      persistentVolumeClaim:
        claimName: ocp4-stig-node-master
    - name: rhcos4-stig-worker-vol
      persistentVolumeClaim:
        claimName: rhcos4-stig-worker
    - name: rhcos4-stig-master-vol
      persistentVolumeClaim:
        claimName: rhcos4-stig-master
