apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vmbr0-enp6s21-policy 
spec:
  desiredState:
    interfaces:
      - name: vmbr0 
        description: Linux bridge with enp6s21 as a port 
        type: linux-bridge 
        state: up 
        ipv4:
          enabled: false 
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: enp6s21
