---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ceph-net-shim-compute-1
  namespace: openshift-storage
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
    kubernetes.io/hostname: m1.cluster.lab.lan # Since these are stataic IP's, each node will need it's own nncp
  desiredState:
    interfaces: # A “shim” interface is used to connect hosts to the Multus public network using the same technology as the Network Attachment Definition will use
      - name: odf-net-shim
        description: Shim interface used to connect host to OpenShift Data Foundation public/cluster Multus network
        type: mac-vlan
        state: up
        mac-vlan:
          base-iface: enp6s19 # The base physical network interface to use
          mode: bridge
          promiscuous: true
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: 172.16.252.1 # The static IP that the node will use
              prefix-length: 23
    routes:
      config:
        - destination: 172.16.0.0/16 # A route so the nodes can get to all ceph pods 
          next-hop-interface: odf-net-shim
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ceph-net-shim-compute-2
  namespace: openshift-storage
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
    kubernetes.io/hostname: m2.cluster.lab.lan
  desiredState:
    interfaces:
      - name: odf-net-shim
        description: Shim interface used to connect host to OpenShift Data Foundation public/cluster Multus network
        type: mac-vlan
        state: up
        mac-vlan:
          base-iface: enp6s19 
          mode: bridge
          promiscuous: true
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: 172.16.252.2
              prefix-length: 23
    routes:
      config:
        - destination: 172.16.0.0/16
          next-hop-interface: odf-net-shim
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ceph-net-shim-compute-3
  namespace: openshift-storage
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
    kubernetes.io/hostname: m3.cluster.lab.lan 
  desiredState:
    interfaces:
      - name: odf-net-shim
        description: Shim interface used to connect host to OpenShift Data Foundation public/cluster Multus network
        type: mac-vlan
        state: up
        mac-vlan:
          base-iface: enp6s19
          mode: bridge
          promiscuous: true
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: 172.16.252.3
              prefix-length: 23
    routes:
      config:
        - destination: 172.16.0.0/16
          next-hop-interface: odf-net-shim
