apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: odf-net
  namespace: openshift-storage
spec:
  config: '{
     "cniVersion": "0.3.1",
     "type": "macvlan",
     "master": "odf-pub-shim",
     "mode": "bridge",
     "ipam": {
       "type": "whereabouts",
       "range": "172.16.0.0/16",
       "exclude": [
          "172.16.252.0/23"
       ],
       "routes": [
         {"dst": "172.16.252.0/23"}
       ]
     }
   }'
