apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond1
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces: # Set interfaces to up
    - name: eno3
      type: ethernet
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false
    - name: eno4
      type: ethernet
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false
    
    - name: bond1 # Create the bond with the ethernet interfaces
      type: bond
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false
      link-aggregation:
        mode: 802.3ad
        options:
          miimon: "150"
          xmit_hash_policy: layer2+3
        port:
          - eno3
          - eno4

    - name: ovs-br1 # Create the OVS bridge on the bond
      description: |-
        A dedicated OVS bridge with bond1 as the ports
        allowing all VLANs and untagged traffic
      type: ovs-bridge
      state: up
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: false
          mcast-snooping-enable: false # Change to true to enable multicast snooping, default is false 
        port:
        - name: bond1
    
    ovn:
      bridge-mappings: # Map the ovs bridge to a localnet, example here is called localnet-trunk
      - localnet: localnet-trunk
        bridge: ovs-br1 
        state: present
      
