apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Basic bridge connection for VMs
  name: bridge
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.4.0", 
      "name": "localnet-trunk", 
      "topology": "localnet", 
      "netAttachDefName": "default/bridge",
      "physicalNetworkName": "localnet-trunk",
      "type": "ovn-k8s-cni-overlay"
    }
