apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: worker1-storage-network-policy
spec:
  nodeSelector: # Use node selectors to target nodes with specific IP addresses
    kubernetes.io/hostname: worker1.cluster.example.com # Here we tell the nncp which node to apply it to
  desiredState:
    interfaces:
    - name: eno2 # Specify the base iface to be up with no ip configuration
      type: ethernet
      state: up
      mtu: 9000 # Optional: Set the MTU on the base iface
      ipv4:
        enabled: false
      ipv6:
        enabled: false
    - name: eno2.18 # Whatever your interface is called plus the vlan tag as an identifier
      description: VLAN 18 using eno2 - 192.168.18.1 # You can give it a good description to logically map everything
      type: vlan
      state: up
      mtu: 9000 # Optional: Also set the MTU on the vlan sub-iface
      ipv4:
        enabled: true
        dhcp: false
        address:
          - ip: 192.168.18.1 # The IP address of this node on the vlan 
            prefix-length: 24
      ipv6:
        enabled: false
      vlan:
        base-iface: eno2 # Whatever your interface is called
        id: 18 # The vlan tag to assign
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: worker2-storage-network-policy
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2.cluster.example.com
  desiredState:
    interfaces:
    - name: eno2
      type: ethernet
      state: up
      mtu: 9000
      ipv4:
        enabled: false
      ipv6:
        enabled: false
    - name: eno2.18
      description: VLAN 18 using eno2 - 192.168.18.2
      type: vlan
      state: up
      mtu: 9000
      ipv4:
        enabled: true
        dhcp: false
        address:
          - ip: 192.168.18.2 
            prefix-length: 24
      ipv6:
        enabled: false
      vlan:
        base-iface: eno2
        id: 18
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: worker3-storage-network-policy
spec:
  nodeSelector:
    kubernetes.io/hostname: worker3.cluster.example.com
  desiredState:
    interfaces:
    - name: eno2
      type: ethernet
      state: up
      mtu: 9000
      ipv4:
        enabled: false
      ipv6:
        enabled: false
    - name: eno2.18
      description: VLAN 18 using eno2 - 192.168.18.3
      type: vlan
      state: up
      mtu: 9000
      ipv4:
        enabled: true
        dhcp: false
        address:
          - ip: 192.168.18.3
            prefix-length: 24
      ipv6:
        enabled: false
      vlan:
        base-iface: eno2
        id: 18