hosts:
- hostname: w4.ocp.lab.io
  rootDeviceHints:
    deviceName: /dev/sda
  role: worker
  interfaces:
  - macAddress: 00:50:56:AF:F3:E7
    name: eth0
  networkConfig:
    interfaces:
      - name: eth0
        type: ethernet
        state: up
        mac-address: 00:50:56:AF:F3:E7
        ipv4:
          enabled: true
          address:
            - ip: 10.1.1.7
              prefix-length: 24
          dhcp: false
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.1.1.254
          next-hop-interface: eth0
          table-id: 254
    dns-resolver:
      config:
        server:
        - 10.1.1.254
